version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  userapi:
    build:
      context: .
      dockerfile: ./cmd/userapi/Dockerfile
    ports:
      - "8080:8080"
    entrypoint: /app/userapi